apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-xasdb-configmap
data:
  MONGO_BACKUP: /dls/science/groups/das/xasdb/xasdb_backup/
  MONGO_DB_HOST: mongo-xasdb-service.eir17846
  MONGO_DB_PORT: "27017"