apiVersion: apps/v1
kind: Deployment
metadata:
  name: xasdb-mongo-express
  labels:
    app: xasdb-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xasdb-mongo-express
  template:
    metadata:
      labels:
        app: xasdb-mongo-express
    spec:
      containers:
      - name: xasdb-mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-xasdb-configmap
              key: MONGO_DB_HOST
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-admin-secret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-admin-secret
              key: password
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: xasdb-mongo-express-service
spec:
  selector:
    app: xasdb-mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081