
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-xasdb
    release: test
  name: mongo-xasdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-xasdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-xasdb
    spec:
      containers:
      - image: mongo:5
        name: mongo
        args: ["--dbpath","/data/db"]
        livenessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: MONGO_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-xasdb-configmap
              key: MONGO_DB_HOST
        - name: MONGO_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-xasdb-configmap
              key: MONGO_DB_PORT
        - name: MONGO_BACKUP
          valueFrom:
            configMapKeyRef:
              name: mongo-xasdb-configmap
              key: MONGO_BACKUP
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-admin-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-admin-secret
              key: password
        volumeMounts:
        - name: mongo-data-dir
          mountPath: "/data/db"
      volumes:
        - name: mongo-data-dir
          emptyDir: {}

---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-xasdb
  name: mongo-xasdb-service
spec:
  ports:
  - name: http
    ports:
    - name: http
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongo-xasdb