
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-xasdb
    release: test
  name: mongo-xasdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-xasdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-xasdb
    spec:
      containers:
      - image: mongo:5
        name: mongo
        args: ["--dbpath","/data/db"]
        livenessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        envFrom:
          - configMapRef:
              name: mongo-xasdb-configmap
        volumeMounts:
        - name: mongo-data-dir
          mountPath: "/data/db"
      volumes:
        - name: mongo-data-dir
          emptyDir: {}