apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1102814
            runAsGroup: 1102814
            supplementalGroups:
              - 37900
          containers:
          - name: hello
            securityContext:
              privileged: false
            image: busybox
            command: ["/bin/sh"]
            args: ["-c", "date > /dls/science/groups/das/xasdb/log.txt"]
            volumeMounts:
              - mountPath: /dls
                name: dls
                mountPropagation: HostToContainer
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          volumes:
            - name: dls
              hostPath:
                path: /dls
                type: Directory