"""
Django settings for xas_database_v2 project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# # for local run
# DEBUG = True
# for K8s run
DEBUG = eval(os.environ.get('DEBUG'))

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = '8lu*6g0lg)9z!ba+a$ehk)xt)x%rxgb$i1&amp;022shmi1jcgihb*'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application definition

INSTALLED_APPS = [
    'xasdb1.apps.Xasdb1Config',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',  # https://github.com/un1t/django-cleanup
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xasdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'xasdb.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# # This section is valid for local run!
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.0/howto/static-files/
# ABSOLUTE_PATH = lambda x: os.path.join(os.path.abspath(os.path.dirname(__file__)), '..', x)
#
# STATIC_URL = '/static/'
# STATIC_ROOT = ABSOLUTE_PATH('static/')
#
# # allow inactive users
# AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']
#
# MEDIA_ROOT = ABSOLUTE_PATH('media/')
# FILE_UPLOAD_PERMISSIONS = 0o600
# FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o700

# This section is valid for K8s run!
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = os.environ.get('STATIC_URL')
STATIC_ROOT = os.environ.get('STATIC_ROOT')

# allow inactive users
AUTHENTICATION_BACKENDS = [os.environ.get('AUTHENTICATION_BACKENDS')]

MEDIA_ROOT = os.environ.get('MEDIA_ROOT')
FILE_UPLOAD_PERMISSIONS = int(os.environ.get('FILE_UPLOAD_PERMISSIONS'), 8)
FILE_UPLOAD_DIRECTORY_PERMISSIONS = int(os.environ.get('FILE_UPLOAD_DIRECTORY_PERMISSIONS'), 8)


# email stuff
# ADMINS = [('Tom Schoonjans', 'Tom.Schoonjans@diamond.ac.uk')]
ADMINS = [('Victor Rogalev', 'victor.rogalev@diamond.ac.uk')]
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_SUBJECT_PREFIX = '[XASDB] '
SERVER_EMAIL = "donotreply@xasdb.diamond.ac.uk"
DEFAULT_FROM_EMAIL = SERVER_EMAIL

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'