# Generated by Django 2.2.4 on 2019-08-14 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import xasdb1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XASFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[xasdb1.models.file_size_valid, xasdb1.models.xdi_valid])),
                ('upload_file_doi', models.CharField(default='', max_length=256, validators=[xasdb1.models.doi_valid], verbose_name='Citation DOI')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('element', models.CharField(max_length=3, validators=[xasdb1.models.mendeljev_valid])),
                ('edge', models.SmallIntegerField(choices=[(0, 'K'), (1, 'L1'), (2, 'L2'), (3, 'L3')], default=0)),
                ('review_status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('sample_name', models.CharField(default='unknown', max_length=100)),
                ('sample_prep', models.CharField(default='unknown', max_length=1000)),
                ('beamline_name', models.CharField(default='unknown', max_length=100)),
                ('facility_name', models.CharField(default='unknown', max_length=100)),
                ('mono_name', models.CharField(default='unknown', max_length=30)),
                ('mono_d_spacing', models.CharField(default='unknown', max_length=30)),
                ('scan_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('refer_used', models.BooleanField(default=False)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XASUploadAuxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aux_description', models.CharField(default='', max_length=256, verbose_name='Description')),
                ('aux_file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[xasdb1.models.file_size_valid])),
                ('aux_thumbnail', models.TextField(blank=True)),
                ('aux_image', models.TextField(blank=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xasdb1.XASFile')),
            ],
        ),
        migrations.CreateModel(
            name='XASMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.SmallIntegerField(choices=[(-1, 'Unknown'), (0, 'Transmission'), (1, 'Fluorescence'), (2, 'Fluorescence, unitstep'), (3, 'Normalized absorption spectrum')], default=-1)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xasdb1.XASFile')),
            ],
        ),
        migrations.CreateModel(
            name='XASDownloadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date downloaded')),
                ('downloader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xasdb1.XASFile')),
            ],
        ),
        migrations.CreateModel(
            name='XASDownloadAuxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date downloaded')),
                ('downloader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xasdb1.XASUploadAuxData')),
            ],
        ),
        migrations.CreateModel(
            name='XASArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', models.TextField()),
                ('unit', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xasdb1.XASFile')),
            ],
        ),
    ]
