# Generated by Django 2.0.5 on 2018-05-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XASFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
