# Generated by Django 2.0.5 on 2018-06-07 16:01

from django.db import migrations, models
import xasdb1.models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xasfile',
            name='atomic_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xasfile',
            name='upload_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[xasdb1.models.xdi_valid]),
        ),
    ]
