# Generated by Django 2.0.5 on 2018-06-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0003_auto_20180611_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xasarray',
            name='id',
        ),
        migrations.AlterField(
            model_name='xasarray',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
