# Generated by Django 2.0.5 on 2018-06-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0004_auto_20180611_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='xasfile',
            name='sample_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
