# Generated by Django 2.0.5 on 2018-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0005_xasfile_sample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='xasarray',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xasarray',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
