# Generated by Django 2.0.5 on 2018-06-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0008_xasmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xasmode',
            name='file',
        ),
        migrations.DeleteModel(
            name='XASMode',
        ),
    ]
