# Generated by Django 2.0.5 on 2018-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0010_xasmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='xasfile',
            name='refer_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='xasmode',
            name='mode',
            field=models.SmallIntegerField(choices=[(-1, 'Unknown'), (0, 'Transmission'), (1, 'Fluorescence'), (2, 'Fluorescence, unitstep')], default=-1),
        ),
    ]
