# Generated by Django 2.0.5 on 2018-06-20 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0011_auto_20180619_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='xasfile',
            name='mono_d_spacing',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='xasfile',
            name='mono_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='xasfile',
            name='sample_prep',
            field=models.CharField(default='unknown', max_length=1000),
        ),
        migrations.AddField(
            model_name='xasfile',
            name='scan_start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 15, 54, 41, 99201, tzinfo=utc)),
        ),
    ]
