# Generated by Django 2.0.5 on 2018-06-21 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0012_auto_20180620_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xasfile',
            name='scan_start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 8, 31, 31, 334500, tzinfo=utc)),
        ),
    ]
