# Generated by Django 2.0.5 on 2018-06-21 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0013_auto_20180621_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xasfile',
            name='scan_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
