# Generated by Django 2.0.5 on 2018-06-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0014_auto_20180621_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='xasfile',
            name='upload_file_doi',
            field=models.CharField(default='', max_length=256, verbose_name='Citation DOI'),
        ),
    ]
