# Generated by Django 2.0.5 on 2018-06-22 14:49

from django.db import migrations, models
import xasdb1.models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0015_xasfile_upload_file_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xasfile',
            name='upload_file_doi',
            field=models.CharField(default='', max_length=256, validators=[xasdb1.models.doi_valid], verbose_name='Citation DOI'),
        ),
    ]
