# Generated by Django 2.1.4 on 2018-12-11 10:19

from django.db import migrations, models
import xasdb1.models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0019_auto_20180720_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xasfile',
            name='upload_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[xasdb1.models.file_size_valid, xasdb1.models.xdi_valid]),
        ),
        migrations.AlterField(
            model_name='xasuploadauxdata',
            name='aux_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', validators=[xasdb1.models.file_size_valid]),
        ),
    ]
