# Generated by Django 2.1.2 on 2018-12-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xasdb1', '0021_xasdownloaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='XASDownloadAuxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date downloaded')),
                ('downloader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xasdb1.XASUploadAuxData')),
            ],
        ),
        migrations.RenameModel(
            old_name='XASDownloadData',
            new_name='XASDownloadFile',
        ),
    ]
