# Generated by Django 2.1.2 on 2018-12-13 17:17

from django.db import migrations, models
import xasdb1.models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0022_auto_20181212_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xasfile',
            name='atomic_number',
        ),
        migrations.AlterField(
            model_name='xasfile',
            name='edge',
            field=models.SmallIntegerField(choices=[(0, 'K'), (1, 'L1'), (2, 'L2'), (3, 'L3')], default=0),
        ),
        migrations.AlterField(
            model_name='xasfile',
            name='element',
            field=models.CharField(max_length=3, validators=[xasdb1.models.mendeljev_valid]),
        ),
    ]
