# Generated by Django 2.1.2 on 2018-12-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0023_auto_20181213_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xasfile',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
