# Generated by Django 2.2.1 on 2019-08-08 14:12

from django.db import migrations, models
import xasdb1.models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0024_auto_20181220_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xasuploadauxdata',
            name='aux_description',
            field=models.CharField(default='', max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='xasuploadauxdata',
            name='aux_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[xasdb1.models.file_size_valid]),
        ),
    ]
