# Generated by Django 2.2.1 on 2019-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xasdb1', '0025_auto_20190808_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='xasuploadauxdata',
            name='aux_thumbnail_file',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
