apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-admin-secret
  namespace: eir17846
spec:
  encryptedData:
    password: AgCZN65PvlA54qTJUCeVDEkhOGZEghUIzh1i3DPnukt4ry6WXCCc0LAzRnGkIdTZqUCb5dFzD6CmN8eNujg68xIIvbDu9MWc++KvIcfYVYdAyrkruvWjbOD4rXNxbrwbvMVZMfwNzv9W6FaRdTtqDUHlY5AT8J/ajaeUEyNpiwJlM2X79DW7Rzc1tDg8dY3i7P2DMM7ami7aVOD8EmUIRup/Z6+AJYjpIKSEZTt31BPxqqtAujHHXpAQz7YiaohDpqCun4uUzE6sTWGiwBrRhgSkJdqXCLnGhGkh6+nDLitr0hh7/giVKG4/PTdv2ZdrewTl/N8LRiX7vb2DFgT65DyoH5Y7FWas2Cfq4t49I5BC3JndOvcfKWmt7JCYT4T8J17FdX0IiWN75Lhp1AnaejPreP7rLt4Acg6SvLOuh2XWzr41OQ0DAqCEN2aqmuIOFQGtDWwN7RvcV9qYGkBZPKn7MuGtJg+zGrc/9F3cbGGYkNviVzGf+YBqPKzx87Z4RjJIkSyJe5K3IwlzYliDcs7YWwUxr7e+NJEhJkAZtxM1s1X5wELkSql/Sxvtsa1jaqHk9eCpDuVRLpytKLtu80xx4zA9B/oAZs7jqKZfI47KczgLDoJr2aOxY1pMKrAN+JjRcLkYpPLK5qLHuZTc2tLWH6RuFsrMCnSdmzmxv9oVG8nnzTys0C0rgMxPKdVaDEG7sa9B9MPpbNurB+j/asvQpO/zusNF
    username: AgAmF9ERuAJsVt4eTaLZV+AWUGgGWggL1QDrEDxCjk5z7i2EauYxhqiXI04YXv1/pGhMUamwbuuGwWAIcEmZHzkAthp3QMby2mkj/DFeHPVGTzGS/vt8DUknL7qdeXYKPCmDCNAzChZOiKVYlm4hYDXo5LmbhnVF0tZrxz3rXpwKPL0Zu47OjiBkgF2+9i9Gi5ywNi0BGDYU0CzkLn8j/ZKkldhYCmXxURV0E8z/v3OHXkkF0KJhYkuUDmzeQy7bDl8qxWrZamxvnBxWZPrkXUli/1f0SLpKXU6iIvQkqaK9sCfUAhcOVGS0QtLl2WTtgLbMbm28HbfMA1Y0kK8S+XS2ViGEvkZuRmR/BFqwgXnRAHGL4GkSbsvfPJA2JGJMrqCy3x/u4nwkkB5ICMHgspfkzHF77oszx+bS2/N4wed0RtGI6rjmIdSFwfl0swTBFYmXMdQpQfVhe0F144A/x/r13+YfMHLZX168Wc+MeuryN4ROUDrP8uCgK8uncM4JdO7CPHtiac9Sp+T+IdMG3pkNzIzsycfuts4h/soozBF+IQX3ikwSQkivpUjK9WxtCxYB1l0H8PmZh2qhYlGG2YH0n/MR80MQ3IpwcWlf8+NyWRhiBaCYzwDNkqGE1V+FlkCSjA0gPLuszGYVCTZr62rVPWLwAB0k1tSlBJwbg7n+BDPDg5zxQOHcJnhlg8F7LFhzRPUY9l9hXwbRpSOTjyc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-admin-secret
      namespace: eir17846